# Generated by Django 6.0.1 on 2026-01-18 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetodoBanco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_banco', models.CharField(max_length=100)),
                ('titular', models.CharField(max_length=100)),
                ('iban', models.CharField(max_length=50)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MetodoExpress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_servico', models.CharField(default='Express', max_length=100)),
                ('numero_telefone', models.CharField(max_length=20)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MetodoReferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=100)),
                ('entidade', models.CharField(max_length=20)),
                ('referencia', models.CharField(max_length=20)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='configuracaosistema',
            name='bancos_disponiveis',
        ),
        migrations.RemoveField(
            model_name='rodada',
            name='total_apostado_global',
        ),
        migrations.RemoveField(
            model_name='saque',
            name='metodo_saque',
        ),
        migrations.AlterField(
            model_name='aposta',
            name='valor_escolhido',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='saque',
            name='status',
            field=models.CharField(default='PENDENTE', max_length=20),
        ),
    ]
